import sys
import os
import time
import argparse

# Add the project root directory to PYTHONPATH
sys.path.insert(
    0,
    os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "..",
            ".."
        )
    )
)

import numpy as np
import pandas as pd
import xgboost as xgb

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

from src.verification.boite import Boite
from src.verification.build_boite import BoitePropagator
from src.verification.stable_improve import StabilityChecker
from src.verification.boite_model import CorrectedBoxClassifier


"""
Usage:

python3 src/experiences/experience_corrected_model.py \
    <model.json> \
    <dataset.csv>

Example:

python3 src/experiences/experience_corrected_model.py \
    models/CPU.json \
    datasets_encoded/CPU.csv

Optional output directory:

python3 src/experiences/experience_corrected_model.py \
    models/CPU.json \
    datasets_encoded/CPU.csv \
    -o models_box
"""


# =============================================================
# LABEL PREPARATION
# =============================================================

def prepare_labels(y):
    """
    Ensure that class labels are represented by consecutive
    integers starting from 0.

    Example:
        [1, 2, 3] -> [0, 1, 2]

    If labels are already [0, ..., K-1], they are kept unchanged.
    """

    y = np.asarray(y)

    unique_y = np.sort(
        np.unique(y)
    )

    expected = np.arange(
        len(unique_y)
    )

    if not np.array_equal(
        unique_y,
        expected
    ):

        print(
            "⚠️ Non-consecutive labels detected. "
            "Applying LabelEncoder."
        )

        encoder = LabelEncoder()

        y = encoder.fit_transform(
            y
        )

    return y


# =============================================================
# ORIGINAL XGBOOST MODEL PREDICTION
# =============================================================

def predict_xgboost_model(
    model_path,
    X
):
    """
    Load the original XGBoost model and predict the classes.

    The function supports both:
      - multi:softmax outputs;
      - multi:softprob outputs.
    """

    model = xgb.Booster()

    model.load_model(
        model_path
    )

    # Keep the same feature names as those used during training
    feature_names = (
        model.feature_names
    )

    dmatrix = xgb.DMatrix(
        X,
        feature_names=feature_names
    )

    predictions = model.predict(
        dmatrix
    )

    # If the model returns one probability vector per sample,
    # convert probabilities to class identifiers.
    if (
        isinstance(predictions, np.ndarray)
        and predictions.ndim == 2
    ):

        predictions = np.argmax(
            predictions,
            axis=1
        )

    return np.asarray(
        predictions,
        dtype=int
    )


# =============================================================
# CORRECTED BOX MODEL PREDICTION
# =============================================================

def predict_box_model(
    model_box,
    X
):
    """
    Predict all dataset instances using the corrected
    box-based classifier.
    """

    predictions = []

    for x in X:

        prediction = model_box.predict(
            x
        )

        predictions.append(
            prediction
        )

    return np.asarray(
        predictions
    )


# =============================================================
# STABILITY VERIFICATION
# =============================================================

def verify_stability(
    dataset_path,
    model_path
):
    """
    Verify whether the original model satisfies the experimental
    stability criterion of at least 90% for every class.

    Returns:
        stable_90
        corrected_boxes
        features
        StabilityChecker
        BoitePropagator
    """

    print(
        "\n============================================"
    )

    print(
        "STABILITY VERIFICATION"
    )

    print(
        "============================================"
    )

    # Build the initial box from the dataset
    initial_box = (
        Boite.creer_boite_initiale_depuis_dataset(
            dataset_path
        )
    )

    # Build the propagator
    propagator = BoitePropagator(
        model_path,
        initial_box
    )

    # Propagate the initial box through the model
    results = propagator.run()

    if not results:

        raise RuntimeError(
            "No final box was generated by the propagator."
        )

    # For an ordinary encoded dataset, the first element
    # corresponds to the generated final boxes.
    final_boxes = (
        BoitePropagator
        .regrouper_boites_par_classe(
            results[0]
        )
    )

    # Run the stability verification
    stability_checker = StabilityChecker(
        final_boxes,
        propagator,
        model_path
    )

    (
        stable_90,
        corrected_boxes,
        features
    ) = stability_checker.verif_stable()

    return (
        stable_90,
        corrected_boxes,
        features,
        stability_checker,
        propagator
    )


# =============================================================
# SAVE REPORT
# =============================================================

def save_report(
    report_path,
    dataset_path,
    original_model_path,
    corrected_model_path,
    stability_checker,
    accuracy_original,
    accuracy_corrected,
    original_size,
    corrected_size,
    execution_time
):
    """
    Save the experimental comparison to a text file.
    """

    size_reduction = (
        original_size
        -
        corrected_size
    )

    if original_size > 0:

        size_reduction_percent = (
            size_reduction
            /
            original_size
        ) * 100

    else:

        size_reduction_percent = 0.0

    accuracy_difference = (
        accuracy_corrected
        -
        accuracy_original
    )

    with open(
        report_path,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            "============================================\n"
        )

        f.write(
            "CORRECTED BOX MODEL EXPERIMENT\n"
        )

        f.write(
            "============================================\n\n"
        )

        f.write(
            f"Dataset: {dataset_path}\n"
        )

        f.write(
            f"Original model: {original_model_path}\n"
        )

        f.write(
            f"Corrected model: {corrected_model_path}\n\n"
        )

        # -----------------------------------------------------
        # STABILITY
        # -----------------------------------------------------

        f.write(
            "STABILITY\n"
        )

        f.write(
            "--------------------------------------------\n"
        )

        f.write(
            "- Formal stability of original model: "
            f"{'YES' if stability_checker.formal_stable else 'NO'}\n"
        )

        f.write(
            "- Experimental stability criterion "
            "(>= 90% for every class): "
            f"{'YES' if stability_checker.stable_90 else 'NO'}\n"
        )

        f.write(
            "- Average stability rate: "
            f"{stability_checker.taux_stability * 100:.2f}%\n"
        )

        f.write(
            "- Stability rate by class:\n"
        )

        for (
            class_id,
            rate
        ) in (
            stability_checker
            .class_stability_rates
            .items()
        ):

            f.write(
                f"    Class {class_id}: "
                f"{rate * 100:.2f}%\n"
            )

        # -----------------------------------------------------
        # ACCURACY
        # -----------------------------------------------------

        f.write(
            "\nACCURACY\n"
        )

        f.write(
            "--------------------------------------------\n"
        )

        f.write(
            "- Original model accuracy: "
            f"{accuracy_original * 100:.2f}%\n"
        )

        f.write(
            "- Corrected model accuracy: "
            f"{accuracy_corrected * 100:.2f}%\n"
        )

        f.write(
            "- Accuracy difference "
            "(corrected - original): "
            f"{accuracy_difference * 100:+.2f}%\n"
        )

        # -----------------------------------------------------
        # MODEL SIZE
        # -----------------------------------------------------

        f.write(
            "\nMODEL SIZE\n"
        )

        f.write(
            "--------------------------------------------\n"
        )

        f.write(
            "- Original model size: "
            f"{original_size:.2f} KB\n"
        )

        f.write(
            "- Corrected model size: "
            f"{corrected_size:.2f} KB\n"
        )

        f.write(
            "- Size reduction: "
            f"{size_reduction:.2f} KB\n"
        )

        f.write(
            "- Size reduction percentage: "
            f"{size_reduction_percent:.2f}%\n"
        )

        # -----------------------------------------------------
        # EXECUTION TIME
        # -----------------------------------------------------

        f.write(
            "\nEXECUTION\n"
        )

        f.write(
            "--------------------------------------------\n"
        )

        f.write(
            "- Total execution time: "
            f"{execution_time:.2f} s\n"
        )

        # -----------------------------------------------------
        # SUMMARY
        # -----------------------------------------------------

        f.write(
            "\nSUMMARY\n"
        )

        f.write(
            "--------------------------------------------\n"
        )

        if accuracy_corrected > accuracy_original:

            f.write(
                "The corrected box-based classifier has a "
                "higher accuracy than the original model.\n"
            )

        elif accuracy_corrected < accuracy_original:

            f.write(
                "The original classifier has a higher "
                "accuracy than the corrected box-based model.\n"
            )

        else:

            f.write(
                "Both classifiers have the same accuracy.\n"
            )

        if corrected_size < original_size:

            f.write(
                "The corrected box-based classifier is "
                "smaller than the original model.\n"
            )

        elif corrected_size > original_size:

            f.write(
                "The corrected box-based classifier is "
                "larger than the original model.\n"
            )

        else:

            f.write(
                "Both models have the same file size.\n"
            )


# =============================================================
# MAIN EXPERIMENT
# =============================================================

def run_experiment(
    model_path,
    dataset_path,
    output_root="models_box"
):
    """
    Complete experiment:

    1. Verify the stability of the original model.
    2. If every class reaches at least 90% stability,
       construct the corrected box-based classifier.
    3. Save the corrected classifier.
    4. Compare original and corrected accuracies.
    5. Compare model sizes.
    6. Save the complete comparison report.
    """

    start_time = time.time()

    # =========================================================
    # CHECK INPUT FILES
    # =========================================================

    if not os.path.isfile(
        model_path
    ):

        raise FileNotFoundError(
            f"Model not found: {model_path}"
        )

    if not os.path.isfile(
        dataset_path
    ):

        raise FileNotFoundError(
            f"Dataset not found: {dataset_path}"
        )

    # =========================================================
    # MODEL NAME AND OUTPUT DIRECTORY
    # =========================================================

    model_name = os.path.splitext(
        os.path.basename(
            model_path
        )
    )[0]

    model_output_dir = os.path.join(
        output_root,
        model_name
    )

    os.makedirs(
        model_output_dir,
        exist_ok=True
    )

    corrected_model_path = os.path.join(
        model_output_dir,
        f"{model_name}_box.json"
    )

    report_path = os.path.join(
        model_output_dir,
        f"{model_name}_comparison.txt"
    )

    print(
        "\n============================================"
    )

    print(
        "CORRECTED MODEL EXPERIMENT"
    )

    print(
        "============================================"
    )

    print(
        "Original model:",
        model_path
    )

    print(
        "Dataset:",
        dataset_path
    )

    print(
        "Output directory:",
        model_output_dir
    )

    # =========================================================
    # LOAD DATASET
    # =========================================================

    dataset = pd.read_csv(
        dataset_path
    )

    X_df = dataset.iloc[
        :,
        :-1
    ]

    y_true = dataset.iloc[
        :,
        -1
    ].values

    # Convert features to numerical values
    X = (
        X_df
        .astype(float)
        .values
    )

    # Prepare labels
    y_true = prepare_labels(
        y_true
    )

    # =========================================================
    # VERIFY ORIGINAL MODEL STABILITY
    # =========================================================

    (
        stable_90,
        corrected_boxes,
        features,
        stability_checker,
        propagator
    ) = verify_stability(
        dataset_path,
        model_path
    )

    print(
        "\nAverage stability rate:",
        f"{stability_checker.taux_stability * 100:.2f}%"
    )

    print(
        "Formal stability:",
        stability_checker.formal_stable
    )

    print(
        "Every class >= 90%:",
        stable_90
    )

    # =========================================================
    # STOP IF THE MODEL DOES NOT REACH 90%
    # =========================================================

    if (
        not stable_90
        or corrected_boxes is None
    ):

        print(
            "\n❌ The corrected model cannot be generated "
            "because the original model does not satisfy "
            "the 90% stability criterion."
        )

        # Save a report even when no model is generated
        with open(
            report_path,
            "w",
            encoding="utf-8"
        ) as f:

            f.write(
                "============================================\n"
            )

            f.write(
                "CORRECTED BOX MODEL EXPERIMENT\n"
            )

            f.write(
                "============================================\n\n"
            )

            f.write(
                f"Dataset: {dataset_path}\n"
            )

            f.write(
                f"Original model: {model_path}\n\n"
            )

            f.write(
                "Corrected model generated: NO\n\n"
            )

            f.write(
                "Reason: the model does not satisfy the "
                "experimental stability criterion of at least "
                "90% for every class.\n\n"
            )

            f.write(
                "Stability rates:\n"
            )

            for (
                class_id,
                rate
            ) in (
                stability_checker
                .class_stability_rates
                .items()
            ):

                f.write(
                    f"Class {class_id}: "
                    f"{rate * 100:.2f}%\n"
                )

        print(
            "Report saved in:",
            report_path
        )

        return

    # =========================================================
    # CREATE CORRECTED BOX CLASSIFIER
    # =========================================================

    print(
        "\n============================================"
    )

    print(
        "BUILDING CORRECTED BOX MODEL"
    )

    print(
        "============================================"
    )

    corrected_model = CorrectedBoxClassifier(
        corrected_boxes,
        features
    )

    # =========================================================
    # SAVE CORRECTED MODEL
    # =========================================================

    corrected_model.save_to_json(
        corrected_model_path
    )

    print(
        "✅ Corrected model saved in:",
        corrected_model_path
    )

    # =========================================================
    # ORIGINAL MODEL ACCURACY
    # =========================================================

    y_pred_original = (
        predict_xgboost_model(
            model_path,
            X
        )
    )

    accuracy_original = (
        accuracy_score(
            y_true,
            y_pred_original
        )
    )

    print(
        "\nOriginal model accuracy:",
        f"{accuracy_original * 100:.2f}%"
    )

    # =========================================================
    # CORRECTED MODEL ACCURACY
    # =========================================================

    y_pred_corrected = (
        predict_box_model(
            corrected_model,
            X
        )
    )

    accuracy_corrected = (
        accuracy_score(
            y_true,
            y_pred_corrected
        )
    )

    print(
        "Corrected box model accuracy:",
        f"{accuracy_corrected * 100:.2f}%"
    )

    # =========================================================
    # MODEL SIZES
    # =========================================================

    original_size = (
        os.path.getsize(
            model_path
        )
        /
        1024.0
    )

    corrected_size = (
        os.path.getsize(
            corrected_model_path
        )
        /
        1024.0
    )

    print(
        "\nOriginal model size:",
        f"{original_size:.2f} KB"
    )

    print(
        "Corrected model size:",
        f"{corrected_size:.2f} KB"
    )

    # =========================================================
    # ACCURACY COMPARISON
    # =========================================================

    difference = (
        accuracy_corrected
        -
        accuracy_original
    )

    if difference > 0:

        print(
            "📈 The corrected box model improves accuracy by",
            f"{difference * 100:.2f} percentage points."
        )

    elif difference < 0:

        print(
            "📉 The corrected box model decreases accuracy by",
            f"{abs(difference) * 100:.2f} percentage points."
        )

    else:

        print(
            "⚖️ Both models have exactly the same accuracy."
        )

    # =========================================================
    # EXECUTION TIME
    # =========================================================

    end_time = time.time()

    execution_time = (
        end_time
        -
        start_time
    )

    # =========================================================
    # SAVE REPORT
    # =========================================================

    save_report(
        report_path=report_path,
        dataset_path=dataset_path,
        original_model_path=model_path,
        corrected_model_path=corrected_model_path,
        stability_checker=stability_checker,
        accuracy_original=accuracy_original,
        accuracy_corrected=accuracy_corrected,
        original_size=original_size,
        corrected_size=corrected_size,
        execution_time=execution_time
    )

    print(
        "\n✅ Comparison report saved in:",
        report_path
    )

    print(
        "\n============================================"
    )

    print(
        "EXPERIMENT COMPLETED"
    )

    print(
        "============================================"
    )


# =============================================================
# COMMAND-LINE ARGUMENTS
# =============================================================

def parse_args(
    argv=None
):
    """
    Parse command-line arguments.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Generate and evaluate a corrected "
            "box-based classifier."
        )
    )

    parser.add_argument(
        "model",
        help=(
            "Path to the original XGBoost JSON model."
        )
    )

    parser.add_argument(
        "dataset",
        help=(
            "Path to the encoded CSV dataset."
        )
    )

    parser.add_argument(
        "-o",
        "--output",
        default="models_box",
        help=(
            "Root directory where corrected models "
            "and reports are stored "
            "(default: models_box)."
        )
    )

    return parser.parse_args(
        argv
    )


# =============================================================
# MAIN
# =============================================================

def main(
    argv=None
):

    args = parse_args(
        argv
    )

    run_experiment(
        model_path=args.model,
        dataset_path=args.dataset,
        output_root=args.output
    )


if __name__ == "__main__":

    main()